//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Topic()
        {
            this.ProductInTopics = new HashSet<ProductInTopic>();
        }
    
        public long ID { get; set; }
        public long UsersID { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public long CommentID { get; set; }
    
        public virtual Comment Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInTopic> ProductInTopics { get; set; }
        public virtual User User { get; set; }
    }
}